/**
 * Shared helpers for the AI-authoring example fixtures (#16).
 *
 * The examples under `examples/<name>/` each ship three files:
 *
 *  - `brief.md`    — the human-authored demo brief (docs only).
 *  - `outline.json`— the structured {@link DeckOutline} an assistant / the MCP
 *    `create_deck_from_outline` tool would produce from that brief.
 *  - `deck.json`   — the expected, normalized deck the outline builds.
 *
 * `deck.json` is compared against the real output of
 * {@link DeckRepository.createDeckFromOutline} — the *same* code path the MCP
 * server uses — so these fixtures lock the authoring contract and catch
 * regressions. Because the builder assigns fresh UUIDs and timestamps on every
 * run, both sides are passed through {@link normalizeForFixture}, which replaces
 * volatile fields (ids, timestamps) with deterministic sentinels. The positional
 * id scheme (`card-1`, `card-1-snippet-2`, …) also implicitly asserts card and
 * snippet ordering.
 *
 * The committed `deck.json` files are generated by `scripts/gen-examples.mjs`,
 * which runs the builder and this normalizer, so they never drift from the code.
 */

import { readFileSync, readdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

import type { Deck } from '../../src/shared'
import type { DeckOutline } from '../../src/cli/deckRepository'

/**
 * Absolute path to the repo's `examples/` directory, resolved from this file's
 * location. Correct when this module runs unbundled (vitest). Callers that run
 * through a bundler (where `import.meta.url` points at a temp file) should pass
 * an explicit dir to {@link listExamples} instead of relying on this constant.
 */
export const EXAMPLES_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'examples')

/** Fixed sentinel written in place of the volatile `createdAt`/`updatedAt`. */
export const FIXTURE_TIMESTAMP = '2000-01-01T00:00:00.000Z'

/** A single example directory and the paths of its three artifacts. */
export interface ExampleFixture {
  /** Directory name under `examples/`, e.g. `saas-onboarding`. */
  name: string
  dir: string
  briefPath: string
  outlinePath: string
  deckPath: string
}

/**
 * Discover every example directory that has an `outline.json`. Pass
 * `examplesDir` to override the default {@link EXAMPLES_DIR} (e.g. from a build
 * script where this module is bundled and its own path is not meaningful).
 */
export function listExamples(examplesDir: string = EXAMPLES_DIR): ExampleFixture[] {
  return readdirSync(examplesDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => {
      const dir = join(examplesDir, e.name)
      return {
        name: e.name,
        dir,
        briefPath: join(dir, 'brief.md'),
        outlinePath: join(dir, 'outline.json'),
        deckPath: join(dir, 'deck.json')
      }
    })
    .filter((ex) => {
      try {
        readFileSync(ex.outlinePath)
        return true
      } catch {
        return false
      }
    })
    .sort((a, b) => a.name.localeCompare(b.name))
}

/** Read and parse an example's `outline.json` as a {@link DeckOutline}. */
export function loadOutline(ex: ExampleFixture): DeckOutline {
  return JSON.parse(readFileSync(ex.outlinePath, 'utf-8')) as DeckOutline
}

/** Read and parse an example's committed expected `deck.json`. */
export function loadExpectedDeck(ex: ExampleFixture): Deck {
  return JSON.parse(readFileSync(ex.deckPath, 'utf-8')) as Deck
}

/**
 * Replace volatile fields (ids, timestamps) with deterministic sentinels so a
 * freshly-built deck can be compared byte-for-byte against a committed fixture.
 *
 * Ids become positional (`deck`, `card-1`, `card-1-snippet-2`), which also
 * asserts card/snippet ordering; timestamps become {@link FIXTURE_TIMESTAMP}.
 * The input is not mutated.
 */
export function normalizeForFixture(deck: Deck): Deck {
  return {
    ...deck,
    id: 'deck',
    createdAt: FIXTURE_TIMESTAMP,
    updatedAt: FIXTURE_TIMESTAMP,
    cards: deck.cards.map((card, ci) => ({
      ...card,
      id: `card-${ci + 1}`,
      snippets: card.snippets.map((snippet, si) => ({
        ...snippet,
        id: `card-${ci + 1}-snippet-${si + 1}`
      }))
    }))
  }
}
